#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cleanCase

paraFoam -touch

#~ runApplication gmshToFoam testMesh.msh

runApplication blockMesh
#~ runApplication topoSet
#~ runApplication refineMesh -overwrite
#~ runApplication decomposePar -force


application=`getApplication`

runApplication $application

#~ runParallel $application

#~ runApplication reconstructPar -newTimes


# ----------------------------------------------------------------- end-of-file
